//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace LouisWebCrawler
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class VirtuemartContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new VirtuemartContainer object using the connection string found in the 'VirtuemartContainer' section of the application configuration file.
        /// </summary>
        public VirtuemartContainer() : base("name=VirtuemartContainer", "VirtuemartContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new VirtuemartContainer object.
        /// </summary>
        public VirtuemartContainer(string connectionString) : base(connectionString, "VirtuemartContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new VirtuemartContainer object.
        /// </summary>
        public VirtuemartContainer(EntityConnection connection) : base(connection, "VirtuemartContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<jos_vm_product> jos_vm_product
        {
            get
            {
                if ((_jos_vm_product == null))
                {
                    _jos_vm_product = base.CreateObjectSet<jos_vm_product>("jos_vm_product");
                }
                return _jos_vm_product;
            }
        }
        private ObjectSet<jos_vm_product> _jos_vm_product;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the jos_vm_product EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTojos_vm_product(jos_vm_product jos_vm_product)
        {
            base.AddObject("jos_vm_product", jos_vm_product);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Virtuemart", Name="jos_vm_product")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class jos_vm_product : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new jos_vm_product object.
        /// </summary>
        /// <param name="product_id">Initial value of the product_id property.</param>
        /// <param name="product_sku">Initial value of the product_sku property.</param>
        public static jos_vm_product Createjos_vm_product(global::System.Int32 product_id, global::System.String product_sku)
        {
            jos_vm_product jos_vm_product = new jos_vm_product();
            jos_vm_product.product_id = product_id;
            jos_vm_product.product_sku = product_sku;
            return jos_vm_product;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String attribute
        {
            get
            {
                return _attribute;
            }
            set
            {
                OnattributeChanging(value);
                ReportPropertyChanging("attribute");
                _attribute = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("attribute");
                OnattributeChanged();
            }
        }
        private global::System.String _attribute;
        partial void OnattributeChanging(global::System.String value);
        partial void OnattributeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        private Nullable<global::System.Int32> cdate
        {
            get
            {
                return _cdate;
            }
            set
            {
                OncdateChanging(value);
                ReportPropertyChanging("cdate");
                _cdate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cdate");
                OncdateChanged();
            }
        }
        private Nullable<global::System.Int32> _cdate;
        partial void OncdateChanging(Nullable<global::System.Int32> value);
        partial void OncdateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        private global::System.String child_options
        {
            get
            {
                return _child_options;
            }
            set
            {
                Onchild_optionsChanging(value);
                ReportPropertyChanging("child_options");
                _child_options = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("child_options");
                Onchild_optionsChanged();
            }
        }
        private global::System.String _child_options;
        partial void Onchild_optionsChanging(global::System.String value);
        partial void Onchild_optionsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        private global::System.String child_option_ids
        {
            get
            {
                return _child_option_ids;
            }
            set
            {
                Onchild_option_idsChanging(value);
                ReportPropertyChanging("child_option_ids");
                _child_option_ids = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("child_option_ids");
                Onchild_option_idsChanged();
            }
        }
        private global::System.String _child_option_ids;
        partial void Onchild_option_idsChanging(global::System.String value);
        partial void Onchild_option_idsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        private global::System.String custom_attribute
        {
            get
            {
                return _custom_attribute;
            }
            set
            {
                Oncustom_attributeChanging(value);
                ReportPropertyChanging("custom_attribute");
                _custom_attribute = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("custom_attribute");
                Oncustom_attributeChanged();
            }
        }
        private global::System.String _custom_attribute;
        partial void Oncustom_attributeChanging(global::System.String value);
        partial void Oncustom_attributeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        private Nullable<global::System.Int32> mdate
        {
            get
            {
                return _mdate;
            }
            set
            {
                OnmdateChanging(value);
                ReportPropertyChanging("mdate");
                _mdate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mdate");
                OnmdateChanged();
            }
        }
        private Nullable<global::System.Int32> _mdate;
        partial void OnmdateChanging(Nullable<global::System.Int32> value);
        partial void OnmdateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        private global::System.String product_availability
        {
            get
            {
                return _product_availability;
            }
            set
            {
                Onproduct_availabilityChanging(value);
                ReportPropertyChanging("product_availability");
                _product_availability = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("product_availability");
                Onproduct_availabilityChanged();
            }
        }
        private global::System.String _product_availability;
        partial void Onproduct_availabilityChanging(global::System.String value);
        partial void Onproduct_availabilityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        private Nullable<global::System.Int32> product_available_date
        {
            get
            {
                return _product_available_date;
            }
            set
            {
                Onproduct_available_dateChanging(value);
                ReportPropertyChanging("product_available_date");
                _product_available_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("product_available_date");
                Onproduct_available_dateChanged();
            }
        }
        private Nullable<global::System.Int32> _product_available_date;
        partial void Onproduct_available_dateChanging(Nullable<global::System.Int32> value);
        partial void Onproduct_available_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        private global::System.String product_desc
        {
            get
            {
                return _product_desc;
            }
            set
            {
                Onproduct_descChanging(value);
                ReportPropertyChanging("product_desc");
                _product_desc = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("product_desc");
                Onproduct_descChanged();
            }
        }
        private global::System.String _product_desc;
        partial void Onproduct_descChanging(global::System.String value);
        partial void Onproduct_descChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        private Nullable<global::System.Int32> product_discount_id
        {
            get
            {
                return _product_discount_id;
            }
            set
            {
                Onproduct_discount_idChanging(value);
                ReportPropertyChanging("product_discount_id");
                _product_discount_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("product_discount_id");
                Onproduct_discount_idChanged();
            }
        }
        private Nullable<global::System.Int32> _product_discount_id;
        partial void Onproduct_discount_idChanging(Nullable<global::System.Int32> value);
        partial void Onproduct_discount_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String product_full_image
        {
            get
            {
                return _product_full_image;
            }
            set
            {
                Onproduct_full_imageChanging(value);
                ReportPropertyChanging("product_full_image");
                _product_full_image = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("product_full_image");
                Onproduct_full_imageChanged();
            }
        }
        private global::System.String _product_full_image;
        partial void Onproduct_full_imageChanging(global::System.String value);
        partial void Onproduct_full_imageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        private Nullable<global::System.Decimal> product_height
        {
            get
            {
                return _product_height;
            }
            set
            {
                Onproduct_heightChanging(value);
                ReportPropertyChanging("product_height");
                _product_height = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("product_height");
                Onproduct_heightChanged();
            }
        }
        private Nullable<global::System.Decimal> _product_height;
        partial void Onproduct_heightChanging(Nullable<global::System.Decimal> value);
        partial void Onproduct_heightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 product_id
        {
            get
            {
                return _product_id;
            }
            set
            {
                if (_product_id != value)
                {
                    Onproduct_idChanging(value);
                    ReportPropertyChanging("product_id");
                    _product_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("product_id");
                    Onproduct_idChanged();
                }
            }
        }
        private global::System.Int32 _product_id;
        partial void Onproduct_idChanging(global::System.Int32 value);
        partial void Onproduct_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        private global::System.Int32 product_in_stock
        {
            get
            {
                return _product_in_stock;
            }
            set
            {
                Onproduct_in_stockChanging(value);
                ReportPropertyChanging("product_in_stock");
                _product_in_stock = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("product_in_stock");
                Onproduct_in_stockChanged();
            }
        }
        private global::System.Int32 _product_in_stock;
        partial void Onproduct_in_stockChanging(global::System.Int32 value);
        partial void Onproduct_in_stockChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        private Nullable<global::System.Decimal> product_length
        {
            get
            {
                return _product_length;
            }
            set
            {
                Onproduct_lengthChanging(value);
                ReportPropertyChanging("product_length");
                _product_length = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("product_length");
                Onproduct_lengthChanged();
            }
        }
        private Nullable<global::System.Decimal> _product_length;
        partial void Onproduct_lengthChanging(Nullable<global::System.Decimal> value);
        partial void Onproduct_lengthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        private global::System.String product_lwh_uom
        {
            get
            {
                return _product_lwh_uom;
            }
            set
            {
                Onproduct_lwh_uomChanging(value);
                ReportPropertyChanging("product_lwh_uom");
                _product_lwh_uom = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("product_lwh_uom");
                Onproduct_lwh_uomChanged();
            }
        }
        private global::System.String _product_lwh_uom;
        partial void Onproduct_lwh_uomChanging(global::System.String value);
        partial void Onproduct_lwh_uomChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String product_name
        {
            get
            {
                return _product_name;
            }
            set
            {
                Onproduct_nameChanging(value);
                ReportPropertyChanging("product_name");
                _product_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("product_name");
                Onproduct_nameChanged();
            }
        }
        private global::System.String _product_name;
        partial void Onproduct_nameChanging(global::System.String value);
        partial void Onproduct_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        private global::System.String product_order_levels
        {
            get
            {
                return _product_order_levels;
            }
            set
            {
                Onproduct_order_levelsChanging(value);
                ReportPropertyChanging("product_order_levels");
                _product_order_levels = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("product_order_levels");
                Onproduct_order_levelsChanged();
            }
        }
        private global::System.String _product_order_levels;
        partial void Onproduct_order_levelsChanging(global::System.String value);
        partial void Onproduct_order_levelsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        private Nullable<global::System.Int32> product_packaging
        {
            get
            {
                return _product_packaging;
            }
            set
            {
                Onproduct_packagingChanging(value);
                ReportPropertyChanging("product_packaging");
                _product_packaging = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("product_packaging");
                Onproduct_packagingChanged();
            }
        }
        private Nullable<global::System.Int32> _product_packaging;
        partial void Onproduct_packagingChanging(Nullable<global::System.Int32> value);
        partial void Onproduct_packagingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        private global::System.Int32 product_parent_id
        {
            get
            {
                return _product_parent_id;
            }
            set
            {
                Onproduct_parent_idChanging(value);
                ReportPropertyChanging("product_parent_id");
                _product_parent_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("product_parent_id");
                Onproduct_parent_idChanged();
            }
        }
        private global::System.Int32 _product_parent_id;
        partial void Onproduct_parent_idChanging(global::System.Int32 value);
        partial void Onproduct_parent_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        private global::System.String product_publish
        {
            get
            {
                return _product_publish;
            }
            set
            {
                Onproduct_publishChanging(value);
                ReportPropertyChanging("product_publish");
                _product_publish = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("product_publish");
                Onproduct_publishChanged();
            }
        }
        private global::System.String _product_publish;
        partial void Onproduct_publishChanging(global::System.String value);
        partial void Onproduct_publishChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        private global::System.Int32 product_sales
        {
            get
            {
                return _product_sales;
            }
            set
            {
                Onproduct_salesChanging(value);
                ReportPropertyChanging("product_sales");
                _product_sales = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("product_sales");
                Onproduct_salesChanged();
            }
        }
        private global::System.Int32 _product_sales;
        partial void Onproduct_salesChanging(global::System.Int32 value);
        partial void Onproduct_salesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String product_sku
        {
            get
            {
                return _product_sku;
            }
            set
            {
                Onproduct_skuChanging(value);
                ReportPropertyChanging("product_sku");
                _product_sku = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("product_sku");
                Onproduct_skuChanged();
            }
        }
        private global::System.String _product_sku;
        partial void Onproduct_skuChanging(global::System.String value);
        partial void Onproduct_skuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        private global::System.String product_special
        {
            get
            {
                return _product_special;
            }
            set
            {
                Onproduct_specialChanging(value);
                ReportPropertyChanging("product_special");
                _product_special = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("product_special");
                Onproduct_specialChanged();
            }
        }
        private global::System.String _product_special;
        partial void Onproduct_specialChanging(global::System.String value);
        partial void Onproduct_specialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        private global::System.String product_s_desc
        {
            get
            {
                return _product_s_desc;
            }
            set
            {
                Onproduct_s_descChanging(value);
                ReportPropertyChanging("product_s_desc");
                _product_s_desc = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("product_s_desc");
                Onproduct_s_descChanged();
            }
        }
        private global::System.String _product_s_desc;
        partial void Onproduct_s_descChanging(global::System.String value);
        partial void Onproduct_s_descChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        private Nullable<global::System.Int32> product_tax_id
        {
            get
            {
                return _product_tax_id;
            }
            set
            {
                Onproduct_tax_idChanging(value);
                ReportPropertyChanging("product_tax_id");
                _product_tax_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("product_tax_id");
                Onproduct_tax_idChanged();
            }
        }
        private Nullable<global::System.Int32> _product_tax_id;
        partial void Onproduct_tax_idChanging(Nullable<global::System.Int32> value);
        partial void Onproduct_tax_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String product_thumb_image
        {
            get
            {
                return _product_thumb_image;
            }
            set
            {
                Onproduct_thumb_imageChanging(value);
                ReportPropertyChanging("product_thumb_image");
                _product_thumb_image = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("product_thumb_image");
                Onproduct_thumb_imageChanged();
            }
        }
        private global::System.String _product_thumb_image;
        partial void Onproduct_thumb_imageChanging(global::System.String value);
        partial void Onproduct_thumb_imageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        private global::System.String product_unit
        {
            get
            {
                return _product_unit;
            }
            set
            {
                Onproduct_unitChanging(value);
                ReportPropertyChanging("product_unit");
                _product_unit = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("product_unit");
                Onproduct_unitChanged();
            }
        }
        private global::System.String _product_unit;
        partial void Onproduct_unitChanging(global::System.String value);
        partial void Onproduct_unitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        private global::System.String product_url
        {
            get
            {
                return _product_url;
            }
            set
            {
                Onproduct_urlChanging(value);
                ReportPropertyChanging("product_url");
                _product_url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("product_url");
                Onproduct_urlChanged();
            }
        }
        private global::System.String _product_url;
        partial void Onproduct_urlChanging(global::System.String value);
        partial void Onproduct_urlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        private Nullable<global::System.Decimal> product_weight
        {
            get
            {
                return _product_weight;
            }
            set
            {
                Onproduct_weightChanging(value);
                ReportPropertyChanging("product_weight");
                _product_weight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("product_weight");
                Onproduct_weightChanged();
            }
        }
        private Nullable<global::System.Decimal> _product_weight;
        partial void Onproduct_weightChanging(Nullable<global::System.Decimal> value);
        partial void Onproduct_weightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        private global::System.String product_weight_uom
        {
            get
            {
                return _product_weight_uom;
            }
            set
            {
                Onproduct_weight_uomChanging(value);
                ReportPropertyChanging("product_weight_uom");
                _product_weight_uom = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("product_weight_uom");
                Onproduct_weight_uomChanged();
            }
        }
        private global::System.String _product_weight_uom;
        partial void Onproduct_weight_uomChanging(global::System.String value);
        partial void Onproduct_weight_uomChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        private Nullable<global::System.Decimal> product_width
        {
            get
            {
                return _product_width;
            }
            set
            {
                Onproduct_widthChanging(value);
                ReportPropertyChanging("product_width");
                _product_width = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("product_width");
                Onproduct_widthChanged();
            }
        }
        private Nullable<global::System.Decimal> _product_width;
        partial void Onproduct_widthChanging(Nullable<global::System.Decimal> value);
        partial void Onproduct_widthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        private global::System.String quantity_options
        {
            get
            {
                return _quantity_options;
            }
            set
            {
                Onquantity_optionsChanging(value);
                ReportPropertyChanging("quantity_options");
                _quantity_options = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("quantity_options");
                Onquantity_optionsChanged();
            }
        }
        private global::System.String _quantity_options;
        partial void Onquantity_optionsChanging(global::System.String value);
        partial void Onquantity_optionsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        private Nullable<global::System.Int32> ship_code_id
        {
            get
            {
                return _ship_code_id;
            }
            set
            {
                Onship_code_idChanging(value);
                ReportPropertyChanging("ship_code_id");
                _ship_code_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ship_code_id");
                Onship_code_idChanged();
            }
        }
        private Nullable<global::System.Int32> _ship_code_id;
        partial void Onship_code_idChanging(Nullable<global::System.Int32> value);
        partial void Onship_code_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        private global::System.Int32 vendor_id
        {
            get
            {
                return _vendor_id;
            }
            set
            {
                Onvendor_idChanging(value);
                ReportPropertyChanging("vendor_id");
                _vendor_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("vendor_id");
                Onvendor_idChanged();
            }
        }
        private global::System.Int32 _vendor_id;
        partial void Onvendor_idChanging(global::System.Int32 value);
        partial void Onvendor_idChanged();

        #endregion
    
    }

    #endregion
    
}
